name: helm-deploy

on:
  workflow_call:
    inputs:
        HELM_TEMPLATE_REPO:
            required: true
            type: string
        HELM_TEMPLATE_BRANCH:
            required: true
            type: string 
        AZ_RESOURCE_GROUP:
            required: true
            type: string
        AZ_AKS_NAME:
            required: true
            type: string
        APP_NAME:
          required: true
          type: string
        APP_VERSION:
          required: true
          type: string
    secrets:
        AZURE_CREDENTIALS:
          required: true

jobs:
  helm-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
            repository: ${{inputs.HELM_TEMPLATE_REPO}} #brightza008/poc-helmchart@minikube
            ref: ${{inputs.HELM_TEMPLATE_BRANCH}}
      - run: |
          ls -R
          echo "Check env"
          helm version

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy TO AKS Cluster
        run: |
            echo "Set context k8s"
            az aks get-credentials --resource-group ${{inputs.AZ_RESOURCE_GROUP}} --name ${{inputs.AZ_AKS_NAME}}
            kubectl get node

            helm repo add azblob https://muzikzzacc.blob.core.windows.net/charts
            helm repo update

            helm upgrade --install my-cherry-chart azblob/${{inputs.APP_NAME}} --values buildchart/values-global.yaml --values buildchart/values-dev.yaml 