name: helm-deploy

on:
  workflow_call:
    
jobs:
  helm-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
            repository: brightza008/poc-helmchart@minikube
      - run: |
          ls -R
          echo "Start Helm!!"
          helm version
