name: Helm build chart

on:
  workflow_call:
    inputs:
      AZURE_STORAGE_ACC_NAME:
          required: true
          type: string
      AZURE_CONTAINER_NAME:
          required: true
          type: string 
      APP_NAME:
          required: true
          type: string
      APP_VERSION:
          required: true
          type: string

jobs:
  run-helm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: helm build chart
        run: | 
          #### HELM ####
          helm dependency update ${{inputs.APP_NAME}}
          helm package ./${{inputs.APP_NAME}}

          #### Start Upload ####
          az storage blob upload \
          --file "./${{inputs.APP_NAME}}-${{inputs.APP_VERSION}}.tgz" \
          --container-name ${{inputs.AZURE_CONTAINER_NAME}} \
          --account-name ${{inputs.AZURE_STORAGE_ACC_NAME}} \
          --auth-mode login

